## Determine which professionals Vanderbilt Hospital should reach out to in the Nashville area to expand their own patient volume.
## First, research which professionals are sending significant numbers of patients only to competitor hospitals (such as TriStar Centennial Medical Center).
## Next, consider the specialty of the provider. If Vanderbilt wants to increase volume from Orthopedic Surgeons or from Family Medicine doctors who should they reach out to in those areas?

In [2]:
import sqlite3
import pandas as pd
#pd.set_option('display.max_rows', None)

### Produce a list of Hospitals with 'Vanderbilt' in the organization name in Nashville TN, not every organization from this list is in Hop table

In [49]:
query = '''
SELECT npi, `provider_organization_name_(legal_business_name)`, 
`provider_business_practice_location_address_city_name`, COUNT(*)
FROM nppes
WHERE `provider_organization_name_(legal_business_name)` LIKE '%Vanderbilt%' 
AND `provider_business_practice_location_address_state_name` = 'TN'
GROUP BY `provider_organization_name_(legal_business_name)`;
'''


with sqlite3.connect('Hop_Teaming_2018.sqlite') as db: 
    test_sqlite = pd.read_sql(query, db)
    
test_sqlite

# Not all organizations from this list appear in HOP dataset

,npi,provider_organization_name_(legal_business_name),provider_business_practice_location_address_city_name,COUNT(*)
0,1891951513,CONCENTRA VANDERBILT LLC,MURFREESBORO,5
1,1881885960,"DOUGLAS L. VANDERBILT, M.D. ,P.C.",CHATTANOOGA,1
2,1255577466,MONROE CARELL JR VANDERBILT CHILDREN'S HOSPITAL,NASHVILLE,1
3,1003211145,MONROE CARELL JR. CHILDREN'S HOSPITAL AT VANDE...,NASHVILLE,1
4,1578646006,VANDERBILT ASTHMA SINUS ALLERGY PROGRAM,NASHVILLE,1
5,1134306244,"VANDERBILT ASTHMA SINUS AND ALLERGY PROGRAM, LLC",NASHVILLE,1
6,1649860305,"VANDERBILT BEDFORD HOSPITAL, LLC",SHELBYVILLE,9
7,1609056399,VANDERBILT CHILDREN'S,NASHVILLE,1
8,1942757307,VANDERBILT CHILDREN'S HOSPITAL PHARMACY,NASHVILLE,1
9,1326224015,VANDERBILT CHILDRENS HOSPITAL,NASHVILLE,1
10,1417543646,"VANDERBILT COFFEE HOSPITAL, LLC",TULLAHOMA,3
11,1265599294,VANDERBILT COMMUNITY AND HOME SERVICES,NASHVILLE,1
12,1619040813,VANDERBILT COMMUNITY MENTAL HEALTH CENTER,NASHVILLE,3
13,1225135551,VANDERBILT HEALTH AND WILLIAMSON MEDICAL CENTE...,FRANKLIN,1
14,1962922435,VANDERBILT HEALTH PHARMACY GROUP LLC,NASHVILLE,1
15,1861638645,VANDERBILT HEART AND VASCULAR INSTITUTE,NASHVILLE,1
16,1235293655,"VANDERBILT HOME CARE SERVICES, LLC",NASHVILLE,1
17,1346532306,VANDERBILT HOSPITAL,CLARKSVILLE,1
18,1457644429,"VANDERBILT IMAGING SERVICES, LLC",NASHVILLE,2
19,1437744828,"VANDERBILT INTEGRATED PROVIDERS, LLC",TULLAHOMA,2
20,1104166313,"VANDERBILT MAURY RADIATION ONCOLOGY, LLC",SPRING HILL,1
21,1164609319,VANDERBILT MEDICAL CENTER,NASHVILLE,5
22,1972749406,VANDERBILT ORTHOPAEDIC INSTITUTE,NASHVILLE,1
23,1285023259,VANDERBILT ORTHOPAEDICS AND REHABILITATION COO...,FRANKLIN,1
24,1992253389,VANDERBILT PSYCHIATRIC HOSPITAL,NASHVILLE,1
25,1255577227,"VANDERBILT PSYCHIATRIC HOSPITAL, LLC",NASHVILLE,1
26,1902989445,"VANDERBILT ST. THOMAS IMAGING, GP",NASHVILLE,1
27,1073608139,VANDERBILT UNIV. MEDICAL CENTER,NASHVILLE,1
28,1396886537,VANDERBILT UNIVERSITY,FRANKLIN,21
29,1427447697,VANDERBILT UNIVERSITY HOSPITAL,NASHVILLE,1
30,1477709053,VANDERBILT UNIVERSITY MEDICAL CENTER,NASHVILLE,38
31,1124017959,VANDERBILT UNIVERSITY MEDICAL SCHOOL,NASHVILLE,1
32,1295832525,VANDERBILT-INGRAM CANCER CENTER AT TENNOVA HEA...,CLARKSVILLE,1

### We learned that 'VANDERBILT UNIVERSITY MEDICAL CENTER' has the most patient referrals from previous tasks. 
### Moreover, 'VANDERBILT UNIVERSITY MEDICAL CENTER' has MANY distinct NPI #. So the next step is to store all npi with organization name 'VANDERBILT UNIVERSITY MEDICAL CENTER' in a list

In [3]:
# Add 'OR `provider_organization_name_(legal_business_name)` = 'SHELBYVILLE HOSPITAL COMPANY LLC' in the WHERE clause if true
query = '''
SELECT GROUP_CONCAT(DISTINCT npi) AS Vanderbilt_npi
FROM nppes
WHERE `provider_organization_name_(legal_business_name)` = 'VANDERBILT UNIVERSITY MEDICAL CENTER'
AND `provider_business_practice_location_address_state_name` = 'TN'
'''


with sqlite3.connect('Hop_Teaming_2018.sqlite') as db: 
    npi_concat_sqlite = pd.read_sql(query, db)
    
Vanderbilt_npi = npi_concat_sqlite.iloc[0][0]
Vanderbilt_npi

'1477709053,1245485200,1366679276,1073833778,1528388196,1801161708,1508132242,1427394634,1336560598,1265833487,1487029997,1902261860,1659738383,1932352283,1912443326,1063958270,1700800877,1538670179,1679971485,1649637794,1013553155,1700950284,1972711828,1285091330,1548920465,1053449660,1144857160,1194186700,1215078027,1215979190,1306889597,1396882205,1558408633,1821030842,1104202761,1770944464,1972027159,1740319847'

## First, research which professionals are sending significant numbers of patients only to competitor hospitals (such as TriStar Centennial Medical Center).

In [4]:
# Get NONE Vandy providers INNER JOIN CCN #
query = f'''
WITH Vandy_providers AS (
    SELECT DISTINCT hop.from_npi
    FROM hop_major_TN_hospitals AS hop
    WHERE hop.to_npi IN ({Vanderbilt_npi}))
SELECT hop.from_npi, hos1.facility_name AS from_facility_affiliation, SUM(patient_count) AS total_patients
FROM hop_major_TN_hospitals AS hop
JOIN nppes AS n
ON n.npi = hop.from_npi
LEFT JOIN facility_affiliations AS fa1
ON hop.from_npi = fa1.npi
LEFT JOIN TN_Hospital_Info AS hos1
ON fa1.facility_afl_ccn = hos1.facility_id
WHERE hop.from_npi NOT IN (SELECT * FROM Vandy_providers)
GROUP BY hop.from_npi
ORDER BY total_patients DESC;
'''


with sqlite3.connect('Hop_Teaming_2018.sqlite') as db: 
    None_Vandy_sqlite_test = pd.read_sql(query, db)
None_Vandy_sqlite_test.head()

     from_npi                from_facility_affiliation  total_patients
0  1417131715     VANDERBILT UNIVERSITY MEDICAL CENTER           31800
1  1912984758                                     None           23500
2  1871548818           TRISTAR SKYLINE MEDICAL CENTER           23045
3  1306993282                                     None           21670
4  1376756742  JACKSON-MADISON COUNTY GENERAL HOSPITAL           20410

In [50]:
# Get NONE Vandy providers
query = f'''
WITH Vandy_providers AS (
    SELECT DISTINCT hop.from_npi
    FROM hop_major_TN_hospitals AS hop
    WHERE hop.to_npi IN ({Vanderbilt_npi}))
SELECT hop.from_npi, SUM(patient_count) AS total_patients, n.*
FROM hop_major_TN_hospitals AS hop
JOIN nppes AS n
ON n.npi = hop.from_npi
WHERE hop.from_npi NOT IN (SELECT * FROM Vandy_providers)
GROUP BY hop.from_npi
ORDER BY total_patients DESC
LIMIT 100;
'''


with sqlite3.connect('Hop_Teaming_2018.sqlite') as db: 
    None_Vandy_sqlite = pd.read_sql(query, db)
None_Vandy_sqlite

,from_npi,total_patients,npi,entity_type_code,provider_organization_name_(legal_business_name),provider_last_name_(legal_name),provider_first_name,provider_middle_name,provider_name_prefix_text,provider_name_suffix_text,provider_credential_text,provider_first_line_business_practice_location_address,provider_second_line_business_practice_location_address,provider_business_practice_location_address_city_name,provider_business_practice_location_address_state_name,provider_business_practice_location_address_postal_code,primary_taxonomy
0,1417131715,6360,1417131715,1.0,None,RIDDICK,JOHN,ALSTON,DR.,None,M.D.,2400 PATTERSON ST,SUITE 502,NASHVILLE,TN,37203,207RI0011X
1,1912984758,4700,1912984758,1.0,None,LASSITER,GREGORY,L,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
2,1871548818,4609,1871548818,1.0,None,KLEIN,WILLIAM,J,DR.,None,MD,7945 WOLF RIVER BLVD,None,GERMANTOWN,TN,38138,2085R0202X
3,1306993282,4334,1306993282,1.0,None,SHIPMAN,JASON,None,None,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
4,1376756742,4082,1376756742,1.0,None,GRIFFIN,BENJAMIN,DAVID,None,None,M.D.,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
5,1447234141,3819,1447234141,1.0,None,CAPLAN,STUART,H,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
6,1821060526,3797,1821060526,1.0,None,WATERS,RONALD,DOUGLAS,DR.,None,M.D.,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
7,1073531042,3768,1073531042,1.0,None,GRIPPO,JAMES,DAVID,DR.,None,M.D.,1224 TROTWOOD AVE,None,COLUMBIA,TN,38401,2085R0202X
8,1487816948,3752,1487816948,1.0,None,PATTERSON,GARY,TRAVIS,DR.,None,M.D.,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
9,1710932017,3735,1710932017,1.0,None,HIMMELFARB,ELLIOT,H,MR.,None,M.D.,3024 BUSINESS PARK CIR,None,GOODLETTSVILLE,TN,37072,2085R0202X
10,1548467319,3652,1548467319,1.0,None,RISSING,MICHAEL,SCOTT,DR.,None,M.D.,1224 TROTWOOD AVE,None,COLUMBIA,TN,38401,2085R0202X
11,1790762219,3568,1790762219,1.0,None,GOODIN,ELLIS,L,DR.,None,M.D.,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
12,1538216403,3531,1538216403,1.0,None,BERKLEY,NATHAN,R,None,None,MD,1224 TROTWOOD AVE,None,COLUMBIA,TN,38401,2085R0202X
13,1912982513,3472,1912982513,1.0,None,FREEMAN,MARK,P,DR.,None,MD,210 25TH AVE N STE 602,None,NASHVILLE,TN,37203,2085R0202X
14,1790730448,3463,1790730448,1.0,None,STAFFORD,JAMES,M,DR.,None,M.D.,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
15,1326023789,3423,1326023789,1.0,None,MOYERS,JOHN,PHILIP,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
16,1508064890,3379,1508064890,1.0,None,SMITH,MARVIN,MONTGOMERY,None,None,M.D.,1224 TROTWOOD AVE,DEPT OF RADIOLOGY,COLUMBIA,TN,38401,2085R0202X
17,1316977861,3337,1316977861,1.0,None,PARKER,KEITH,R,DR.,None,MD,2300 PATTERSON ST,CENTENNIAL MEDICAL CENTER,NASHVILLE,TN,37203,2085R0202X
18,1144216482,3335,1144216482,1.0,None,PATE,JOSEPH,E.,DR.,None,MD,1224 TROTWOOD AVE,None,COLUMBIA,TN,38401,2085R0202X
19,1255318051,3328,1255318051,1.0,None,KING,JOHN,D,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
20,1598751810,3325,1598751810,1.0,None,PODGORSKI,GARY,T.,DR.,None,MD,1224 TROTWOOD AVE,"SOUTHERN RADIOLOGY ASSOCIATES, PLL",COLUMBIA,TN,38401,2085R0202X
21,1396721106,3300,1396721106,1.0,None,BERGER,BRIAN,L,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
22,1750410452,3268,1750410452,1.0,None,YOUNG,ROBERT,STEVEN,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0204X
23,1972549533,3228,1972549533,1.0,None,SMITH,GREGORY,D,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
24,1689617433,3193,1689617433,1.0,None,MASSIE,JAMES,D,DR.,JR.,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
25,1316949191,3119,1316949191,1.0,None,BUTLER,JAMES,BLAIR,DR.,None,MD,1224 TROTWOOD AVE,"SOUTHERN RADIOLOGY ASSOCIATES, PLLC",COLUMBIA,TN,38401,2085R0202X
26,1366599243,3085,1366599243,1.0,None,GRIPPO,DANIEL,AARON,None,None,MD,1224 TROTWOOD AVE,None,COLUMBIA,TN,38401,2085R0202X
27,1144283896,3036,1144283896,1.0,None,TEPPER,PATRICIA,ANN,None,None,M.D.,210 25TH AVE N,SUITE 602,NASHVILLE,TN,37203,2085R0202X
28,1649292160,3029,1649292160,1.0,None,BREWER,WILLIAM,WESLEY,None,None,M.D.,1224 TROTWOOD AVENUE,"SOUTHERN RADIOLOGY ASSOCIATES, PLLC",COLUMBIA,TN,38401,2085R0202X
29,1245215649,3008,1245215649,1.0,None,HOLBROOK,JAMES,T,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
30,1043522311,3008,1043522311,1.0,None,LONG,SCOTT,HOLMES,None,None,M.D.,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
31,1972800282,3007,1972800282,1.0,None,STEPHENSON,MATTHEW,LEE,None,None,MD,22 BRAMHALL ST,None,PORTLAND,ME,04102,2085R0202X
32,1437136827,2980,1437136827,1.0,None,WEAVER,GREGORY,R,DR.,None,MD,210 25TH AVE N STE 602,None,NASHVILLE,TN,37203,2085R0202X
33,1407833825,2962,1407833825,1.0,None,BARTEK,JOHN,G,DR.,None,M.D.,210 25TH AVE N,STE 602,NASHVILLE,TN,37203,2085R0202X
34,1073557831,2947,1073557831,1.0,None,MEYEROWITZ,COLIN,B,None,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
35,1366429151,2899,1366429151,1.0,None,TISHLER,STEVEN,D,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
36,1578541439,2881,1578541439,1.0,None,SHACKELFORD,DAVID,M,None,None,MD,1224 TROTWOOD AVE,None,COLUMBIA,TN,38401,2085R0202X
37,1417091257,2863,1417091257,1.0,None,BRIEN,PATRICK,LIVINGSTON,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
38,1851478747,2860,1851478747,1.0,None,PANZEGRAU,BEATA,None,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
39,1962636068,2858,1962636068,1.0,None,HECK,JOSH,M,DR.,None,M.D.,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
40,1013184340,2829,1013184340,1.0,None,SAVA,MELINDA,RIXEY,None,None,M.D.,3024 BUSINESS PARK CIR,None,GOODLETTSVILLE,TN,37072,2085R0202X
41,1396707923,2825,1396707923,1.0,None,HORN,ALAN,W,None,None,MD,9100 BABCOCK BLVD,None,PITTSBURGH,PA,15237,2085R0202X
42,1689616294,2761,1689616294,1.0,None,BOORGU,KARTIK,None,None,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
43,1598727042,2731,1598727042,1.0,None,FORSYTHE,LOY,ALLEN,DR.,None,MD,651 DUNLOP LN,SUITE 530,CLARKSVILLE,TN,37040,2085R0202X
44,1730473125,2724,1730473125,1.0,None,REED,WILLIAM,J,None,None,MD,4500 SAN PABLO RD S,PROVIDER ENROLLMENT,JACKSONVILLE,FL,32224,2085R0202X
45,1710104484,2716,1710104484,1.0,None,BLOMQUIST,GUSTAV,A,DR.,None,MD,800 ROSE ST,HX318,LEXINGTON,KY,40536,2085R0202X
46,1164656559,2675,1164656559,1.0,None,HEITMAN,JOEL,THOMAS,DR.,None,M.D.,615 S NEW BALLAS RD DEPT OF,None,SAINT LOUIS,MO,63141,2085R0202X
47,1104933738,2654,1104933738,1.0,None,LEE,JUNG,H.,None,None,M.D.,353 NEW SHACKLE ISLAND RD,#300C,HENDERSONVILLE,TN,37075,207RC0000X
48,1225027014,2602,1225027014,1.0,None,KUDELKO,PAUL,EDWARD,DR.,II,DO,353 NEW SHACKLE ISLAND RD,SUITE 300C,HENDERSONVILLE,TN,37075,207RC0000X
49,1043206329,2569,1043206329,1.0,None,MAHONEY,ROBERT,JEFFREY,DR.,None,MD,3601 THE VANDERBILT CLINIC,None,NASHVILLE,TN,37232,2085R0202X
50,1396729091,2529,1396729091,1.0,None,GRAY,SCOTT,D,None,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
51,1942290333,2516,1942290333,1.0,None,DICKERSON,REGINALD,PEELER,None,None,M.D,300 STEAM PLANT RD,SUITE 300,GALLATIN,TN,37066,207RC0000X
52,1720286487,2494,1720286487,1.0,None,ROGERS,LEE,HARTWELL,DR.,JR.,M.D.,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
53,1245557115,2485,1245557115,1.0,None,TRAN,HONG,NGOC,DR.,None,MD,200 W ACADEMY ST NW,None,GAINESVILLE,GA,30501,2085R0202X
54,1013179860,2460,1013179860,1.0,None,YAWN,GARY,WAYNE,DR.,JR.,M.D.,353 NEW SHACKLE ISLAND RD STE 300C,None,HENDERSONVILLE,TN,37075,207RI0011X
55,1316921166,2439,1316921166,1.0,None,ROWE,DAVID,M,DR.,None,MD,210 25TH AVE N STE 602,None,NASHVILLE,TN,37203,2085R0202X
56,1699752493,2400,1699752493,1.0,None,BAKER,JACK,R,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
57,1790891315,2361,1790891315,1.0,None,RUSSO,DONALD,J,None,None,M.D.,353 NEW SHACKLE ISLAND RD,#300C,HENDERSONVILLE,TN,37075,207RC0000X
58,1316236086,2344,1316236086,1.0,None,KHURANA,ANJALI,None,None,None,M.D.,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
59,1669428603,2337,1669428603,1.0,None,BOUGHNER,BRICE,T.,DR.,None,MD,1224 TROTWOOD AVE,None,COLUMBIA,TN,38401,2085R0202X
60,1477542942,2335,1477542942,1.0,None,BURNER,KEVIN,LYN,None,None,M.D.,1801 ASHLEY CIR,None,BOWLING GREEN,KY,42104,2085R0202X
61,1902823859,2319,1902823859,1.0,None,HUNEYCUTT,DAVID,C,DR.,JR.,MD,2400 PATTERSON ST,SUITE 502,NASHVILLE,TN,37203,207RC0000X
62,1619180403,2300,1619180403,1.0,None,DORFMAN,TODD,None,None,None,MD,5651 FRIST BLVD STE 603,None,HERMITAGE,TN,37076,207RC0000X
63,1114243789,2298,1114243789,1.0,None,HARTY,JAMES,PATRICK,None,None,M.D.,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
64,1245325422,2288,1245325422,1.0,None,HAWKINS,KENNETH,None,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
65,1457671760,2272,1457671760,1.0,None,SHANAHAN,PETER,LAWRENCE,DR.,None,M.D.,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
66,1477537173,2228,1477537173,1.0,None,KENNON,JULIE,C,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
67,1275536468,2222,1275536468,1.0,None,ASAD,MUHAMMAD,None,DR.,None,MD,353 NEW SHACKLE ISLAND RD,SUITE 300 C,HENDERSONVILLE,TN,37075,207RC0000X
68,1386938595,2199,1386938595,1.0,None,CHISM,CHARLES,None,None,None,M.D.,6411 FANNIN ST,None,HOUSTON,TX,77030,2085R0202X
69,1053337717,2188,1053337717,1.0,None,KAZA,SUNIL,C,DR.,None,M.D.,3443 DICKERSON PIKE,SUITE 430,NASHVILLE,TN,37207,207RC0000X
70,1114961513,2187,1114961513,1.0,None,HUMPHREY,STEVEN,S,DR.,None,MD,3601 THE VANDERBILT CLINIC,None,NASHVILLE,TN,37232,207RC0000X
71,1447366075,2181,1447366075,1.0,None,LIPPOLIS,NICHOLAS,J.,None,None,M.D.,353 NEW SHACKLE ISLAND RD,#300C,HENDERSONVILLE,TN,37075,207RC0000X
72,1952614729,2159,1952614729,1.0,None,NICHOLS,MICHAEL,None,DR.,None,M.D.,975 E 3RD ST # 376,None,CHATTANOOGA,TN,37403,2085R0202X
73,1639113509,2142,1639113509,1.0,None,WOJCICKI,WALTER,E.,DR.,None,M.D.,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
74,1013991850,2120,1013991850,1.0,None,NG,CHRISTOPHER,C,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
75,1386976207,2119,1386976207,1.0,None,ROTH,JASON,KYLE,DR.,None,MD,INTEGRA IMAGING PS,1200 WESTWOOD DRIVE,HAMILTON,MT,59840,2085R0202X
76,1487934584,2108,1487934584,1.0,None,BARRAZA,JOHN,MICHAEL,DR.,II,M.D.,5000 HENNESSY BLVD,None,BATON ROUGE,LA,70808,2085R0202X
77,1013118702,2090,1013118702,1.0,None,BAZZANI,MICHAEL,D.,DR.,None,M.D.,10010 KENNERLY RD,None,SAINT LOUIS,MO,63128,2085R0202X
78,1972658060,2085,1972658060,1.0,None,KETCH,TERRY,ROBERT,DR.,None,M.D.,3443 DICKERSON PIKE STE 430,None,NASHVILLE,TN,37207,207RC0000X
79,1427079946,2070,1427079946,1.0,None,CONLEY,CHRISTOPHER,N,DR.,None,M.D.,3443 DICKERSON PIKE,SUITE 430,NASHVILLE,TN,37207,207RC0001X
80,1649471780,2056,1649471780,1.0,None,GREENE,ELTON,BENJAMIN,None,None,M.D.,3601 THE VANDERBILT CLINIC,None,NASHVILLE,TN,37232,2085N0700X
81,1659606788,2044,1659606788,1.0,None,BONAMINIO,DANA,N,DR.,None,M.D.,3024 BUSINESS PARK CIR,None,GOODLETTSVILLE,TN,37072,2085R0202X
82,1386683118,2033,1386683118,1.0,None,BLOUNT,STEVEN,MICHAEL,MR.,None,M.D.,3024 BUSINESS PARK CIR,None,GOODLETTSVILLE,TN,37072,2085R0202X
83,1114074085,2002,1114074085,1.0,None,FRISBIE,BRENT,None,None,None,MD,620 HARTSVILLE PIKE,None,GALLATIN,TN,37066,2085R0202X
84,1548466808,1961,1548466808,1.0,None,JONES,MATTHEW,KEITH,DR.,None,M.D.,1265 UNION AVE,None,MEMPHIS,TN,38104,2085R0202X
85,1053366369,1946,1053366369,1.0,None,NABORS,GLENN,F,DR.,JR.,MD,620 HARTSVILLE PIKE,None,GALLATIN,TN,37066,2085R0202X
86,1750366050,1942,1750366050,1.0,None,LUSSNIG,ERICH,None,DR.,None,MD,1700 MEDICAL CENTER PKWY,None,MURFREESBORO,TN,37129,2085R0202X
87,1740235415,1928,1740235415,1.0,None,AREVALOS,ENRIQUE,ROMO,MR.,None,M.D.,3024 BUSINESS PARK CIR,None,GOODLETTSVILLE,TN,37072,2085R0202X
88,1902833940,1925,1902833940,1.0,None,DAME,ERIC,ARTHUR,DR.,None,MD,1113 MURFREESBORO RD,SUITE 106 #343,FRANKLIN,TN,37064,2085R0202X
89,1730111642,1922,1730111642,1.0,None,PATEL,TARAL,NAVINCHANDRA,DR.,None,M.D.,5651 FRIST BLVD STE 603,None,HERMITAGE,TN,37076,207RI0011X
90,1194018531,1886,1194018531,1.0,None,LAYMAN,MATTHEW,SCOTT,DR.,None,M.D.,1700 MEDICAL CENTER PKWY,None,MURFREESBORO,TN,37129,2085R0202X
91,1932194966,1882,1932194966,1.0,None,WILLIAMS,THOMAS,A.,DR.,JR.,M.D.,1532 LONE OAK RD STE 415,None,PADUCAH,KY,42003,207RC0001X
92,1407830102,1855,1407830102,1.0,None,LUSCHEN,MICHELLE,C,DR.,None,MD,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0204X
93,1134225089,1844,1134225089,1.0,None,OWEN,ANN,B,None,None,MD,212 HERITAGE PARK DR,None,MURFREESBORO,TN,37129,2085R0202X
94,1912115197,1835,1912115197,1.0,None,WILLIAMS,BRENT,None,DR.,None,D.O.,741 PRESIDENT PL,None,SMYRNA,TN,37167,2085R0202X
95,1740337633,1815,1740337633,1.0,None,DAY,MATTHEW,None,None,None,MD,210 25TH AVE N STE 602,None,NASHVILLE,TN,37203,2085R0202X
96,1558461970,1805,1558461970,1.0,None,WHEATLEY,ROBERT,M,DR.,None,M.D. F.A.C.C.,2400 PATTERSON ST,SUITE 502,NASHVILLE,TN,37203,207RI0011X
97,1205813573,1768,1205813573,1.0,None,STALLWORTH,JAMES,M.,DR.,None,M.D.,210 25TH AVE N STE 1204,None,NASHVILLE,TN,37203,2085R0202X
98,1326086653,1704,1326086653,1.0,None,GRAVES,DANTE,J.,None,None,M.D.,4230 HARDING RD,SUITE 330,NASHVILLE,TN,37205,207RC0000X
99,1568568319,1697,1568568319,1.0,None,POPE,STAN,L,None,None,MD,212 HERITAGE PARK DR,None,MURFREESBORO,TN,37129,2085R0202X

## Next, consider the specialty of the provider. If Vanderbilt wants to increase volume from Orthopedic Surgeons or from Family Medicine doctors who should they reach out to in those areas?

In [5]:
# Group NONE Vandy providers by specialization
query = f'''
SELECT specialization, total_patients, ROUND(specialization_referral_ratio*100,2) AS referral_pct_total, 
    hos1.facility_name AS from_facility_affiliation, from_df.npi, 
    from_df.`provider_last_name_(legal_name)`, from_df.provider_middle_name, from_df.provider_first_name
FROM (
WITH specialization AS (
    SELECT t.specialization, SUM(h.transaction_count) AS total_transactions, SUM(h.patient_count) AS total_patients
    FROM hop_major_TN_hospitals AS h
    INNER JOIN nppes n1
    ON h.from_npi = n1.npi
    INNER JOIN taxonomy as t
    ON n1.primary_taxonomy = t.code
    GROUP BY t.specialization
),

Vandy_providers AS (
    SELECT DISTINCT h.from_npi
    FROM hop_major_TN_hospitals AS h
    WHERE h.to_npi IN ({Vanderbilt_npi}))
    
SELECT t. specialization, SUM(patient_count) AS total_patients, 
       s.total_patients AS specialization_total_patients_ref,
       SUM(h.patient_count)*1.0/s.total_patients AS specialization_referral_ratio,
       n.*
FROM hop_major_TN_hospitals AS h
JOIN nppes AS n
ON n.npi = h.from_npi
JOIN taxonomy AS t
ON t.code = n.primary_taxonomy
INNER JOIN specialization AS s
ON s.specialization = t.specialization 
WHERE h.from_npi NOT IN (SELECT * FROM Vandy_providers)
GROUP BY h.from_npi
ORDER BY t.specialization, total_patients DESC) AS from_df
LEFT JOIN facility_affiliations AS fa1
ON from_df.npi = fa1.npi
LEFT JOIN TN_Hospital_Info AS hos1
ON fa1.facility_afl_ccn = hos1.facility_id;
'''




with sqlite3.connect('Hop_Teaming_2018.sqlite') as db: 
    None_Vandy_byspecialization_affiliation = pd.read_sql(query, db)
None_Vandy_byspecialization_affiliation.head()

,specialization,total_patients,referral_pct_total,from_facility_affiliation,npi,provider_last_name_(legal_name),provider_middle_name,provider_first_name
0,Acute Care,555,2.28,SAINT THOMAS RUTHERFORD HOSPITAL,1649718230,GRABOVICH,None,DANIELLE
1,Acute Care,526,2.16,TRISTAR CENTENNIAL MEDICAL CENTER,1487041513,NEUFELD,DANIEL,LUCAS
2,Acute Care,388,1.59,SAINT THOMAS WEST HOSPITAL,1427334176,GRAUZER,WILLIAM,FRANKLIN
3,Acute Care,347,1.43,SAINT THOMAS RUTHERFORD HOSPITAL,1508892688,PEMBRIDGE,L,RICHARD
4,Acute Care,347,1.43,SAINT THOMAS WEST HOSPITAL,1508892688,PEMBRIDGE,L,RICHARD

## Solution

If Vanderbilt wants to increase volume from Orthopedic Surgeons or from Family Medicine doctors, they may consider reaching out to family medicine providers in top 5 affiliations (see result below) and Orthopedic Surgeons from Saint Thomas and Tristar networks.

In [5]:
# Group NONE Vandy providers by specialization
query = f'''
SELECT specialization, from_facility_affiliation, COUNT(npi) AS providers_count
FROM (
SELECT specialization, total_patients, ROUND(specialization_referral_ratio*100,2) AS referral_pct_total, 
    hos1.facility_name AS from_facility_affiliation, from_df.npi, 
    from_df.`provider_last_name_(legal_name)`, from_df.provider_middle_name, from_df.provider_first_name
FROM (
WITH specialization AS (
    SELECT t.specialization, SUM(h.transaction_count) AS total_transactions, SUM(h.patient_count) AS total_patients
    FROM hop_major_TN_hospitals AS h
    INNER JOIN nppes n1
    ON h.from_npi = n1.npi
    INNER JOIN taxonomy as t
    ON n1.primary_taxonomy = t.code
    GROUP BY t.specialization
),

Vandy_providers AS (
    SELECT DISTINCT h.from_npi
    FROM hop_major_TN_hospitals AS h
    WHERE h.to_npi IN ({Vanderbilt_npi}))
    
SELECT t. specialization, SUM(patient_count) AS total_patients, 
       s.total_patients AS specialization_total_patients_ref,
       SUM(h.patient_count)*1.0/s.total_patients AS specialization_referral_ratio,
       n.*
FROM hop_major_TN_hospitals AS h
JOIN nppes AS n
ON n.npi = h.from_npi
JOIN taxonomy AS t
ON t.code = n.primary_taxonomy
INNER JOIN specialization AS s
ON s.specialization = t.specialization 
WHERE h.from_npi NOT IN (SELECT * FROM Vandy_providers)
GROUP BY h.from_npi
ORDER BY t.specialization, total_patients DESC) AS from_df
LEFT JOIN facility_affiliations AS fa1
ON from_df.npi = fa1.npi
LEFT JOIN TN_Hospital_Info AS hos1
ON fa1.facility_afl_ccn = hos1.facility_id)
WHERE specialization IN ('Family','Orthopaedic Surgery of the Spine')
GROUP BY specialization, from_facility_affiliation;
'''


with sqlite3.connect('Hop_Teaming_2018.sqlite') as db: 
    None_Vandy_byspecialization_affiliation_count = pd.read_sql(query, db)
None_Vandy_byspecialization_affiliation_count

,specialization,from_facility_affiliation,providers_count
0,Family,None,199
1,Family,ASCENSION SAINT THOMAS THREE RIVERS,3
2,Family,BAPTIST MEMORIAL HOSPITAL TIPTON,1
3,Family,DEKALB COMMUNITY HOSPITAL,2
4,Family,HARDIN MEDICAL CENTER,1
5,Family,HENDERSON COUNTY COMMUNITY HOSPITAL,1
6,Family,HENRY COUNTY MEDICAL CENTER,1
7,Family,JACKSON-MADISON COUNTY GENERAL HOSPITAL,1
8,Family,LINCOLN MEDICAL CENTER,1
9,Family,MACON COMMUNITY HOSPITAL,5
10,Family,MARSHALL MEDICAL CENTER,8
11,Family,MAURY REGIONAL HOSPITAL,24
12,Family,"MEMORIAL HEALTHCARE SYSTEM, INC",1
13,Family,PARKRIDGE MEDICAL CENTER,1
14,Family,RIVERVIEW REGIONAL MEDICAL CENTER,3
15,Family,SAINT THOMAS HOSPITAL FOR SPINAL SURGERY,1
16,Family,SAINT THOMAS RIVER PARK HOSPITAL,7
17,Family,SAINT THOMAS RUTHERFORD HOSPITAL,4
18,Family,SAINT THOMAS WEST HOSPITAL,15
19,Family,SOUTHERN TENNESSEE REGIONAL HEALTH SYSTEM LAWR...,6
20,Family,SOUTHERN TENNESSEE REGIONAL HEALTH SYSTEM PULASKI,2
21,Family,SOUTHERN TENNESSEE REGIONAL HLTH SYSTEM WINCHE...,1
22,Family,STONES RIVER HOSPITAL,2
23,Family,SUMNER REGIONAL MEDICAL CENTER,11
24,Family,TENNOVA HEALTHCARE-CLARKSVILLE,2
25,Family,TRISTAR ASHLAND CITY MEDICAL CENTER,2
26,Family,TRISTAR CENTENNIAL MEDICAL CENTER,15
27,Family,TRISTAR HENDERSONVILLE MEDICAL CENTER,7
28,Family,TRISTAR HORIZON MEDICAL CENTER,5
29,Family,TRISTAR NORTHCREST MEDICAL CENTER,3
30,Family,TRISTAR SKYLINE MEDICAL CENTER,5
31,Family,TRISTAR SOUTHERN HILLS MEDICAL CENTER,6
32,Family,TRISTAR STONECREST MEDICAL CENTER,3
33,Family,TRISTAR SUMMIT MEDICAL CENTER,6
34,Family,TROUSDALE MEDICAL CENTER,1
35,Family,UNITY MEDICAL CENTER,1
36,Family,VANDERBILT BEDFORD HOSPITAL,6
37,Family,VANDERBILT TULLAHOMA-HARTON HOSPITAL,3
38,Family,VANDERBILT UNIVERSITY MEDICAL CENTER,10
39,Family,VANDERBILT WILSON COUNTY HOSPITAL,4
40,Family,WAYNE MEDICAL CENTER,3
41,Family,WILLIAMSON MEDICAL CENTER,5
42,Orthopaedic Surgery of the Spine,None,3
43,Orthopaedic Surgery of the Spine,MARSHALL MEDICAL CENTER,1
44,Orthopaedic Surgery of the Spine,MAURY REGIONAL HOSPITAL,3
45,Orthopaedic Surgery of the Spine,SAINT THOMAS HOSPITAL FOR SPINAL SURGERY,1
46,Orthopaedic Surgery of the Spine,SAINT THOMAS WEST HOSPITAL,3
47,Orthopaedic Surgery of the Spine,TRISTAR CENTENNIAL MEDICAL CENTER,2
48,Orthopaedic Surgery of the Spine,TRISTAR HENDERSONVILLE MEDICAL CENTER,3
49,Orthopaedic Surgery of the Spine,TRISTAR SKYLINE MEDICAL CENTER,2
50,Orthopaedic Surgery of the Spine,TRISTAR SOUTHERN HILLS MEDICAL CENTER,1
51,Orthopaedic Surgery of the Spine,TRISTAR STONECREST MEDICAL CENTER,1
52,Orthopaedic Surgery of the Spine,WILLIAMSON MEDICAL CENTER,2

In [6]:
# Group NONE Vandy providers by specialization
query = f'''
WITH specialization AS (
    SELECT t.specialization, SUM(h.transaction_count) AS total_transactions, SUM(h.patient_count) AS total_patients
    FROM hop_major_TN_hospitals AS h
    INNER JOIN nppes n1
    ON h.from_npi = n1.npi
    INNER JOIN taxonomy as t
    ON n1.primary_taxonomy = t.code
    GROUP BY t.specialization
),

Vandy_providers AS (
    SELECT DISTINCT h.from_npi
    FROM hop_major_TN_hospitals AS h
    WHERE h.to_npi IN ({Vanderbilt_npi}))
    
SELECT t. specialization, SUM(patient_count) AS total_patients, 
       s.total_patients AS specialization_total_patients_ref,
       SUM(h.patient_count)*1.0/s.total_patients AS specialization_referral_ratio,
       n.*
FROM hop_major_TN_hospitals AS h
JOIN nppes AS n
ON n.npi = h.from_npi
JOIN taxonomy AS t
ON t.code = n.primary_taxonomy
INNER JOIN specialization AS s
ON s.specialization = t.specialization 
WHERE h.from_npi NOT IN (SELECT * FROM Vandy_providers)
GROUP BY h.from_npi
ORDER BY t.specialization, total_patients DESC ;
'''


with sqlite3.connect('Hop_Teaming_2018.sqlite') as db: 
    None_Vandy_byspecialization_sqlite = pd.read_sql(query, db)
None_Vandy_byspecialization_sqlite.head()

,specialization,total_patients,specialization_total_patients_ref,specialization_referral_ratio,npi,entity_type_code,provider_organization_name_(legal_business_name),provider_last_name_(legal_name),provider_first_name,provider_middle_name,provider_name_prefix_text,provider_name_suffix_text,provider_credential_text,provider_first_line_business_practice_location_address,provider_second_line_business_practice_location_address,provider_business_practice_location_address_city_name,provider_business_practice_location_address_state_name,provider_business_practice_location_address_postal_code,primary_taxonomy
0,Acute Care,555,24337,0.022805,1649718230,1.0,None,GRABOVICH,DANIELLE,None,None,None,APN,1840 MEDICAL CENTER PKWY STE 201,None,MURFREESBORO,TN,37129,363LA2100X
1,Acute Care,526,24337,0.021613,1487041513,1.0,None,NEUFELD,LUCAS,DANIEL,None,None,AGACNP-BC,2300 PATTERSON ST,None,NASHVILLE,TN,37203,363LA2100X
2,Acute Care,388,24337,0.015943,1427334176,1.0,None,GRAUZER,FRANKLIN,WILLIAM,None,None,APN,4230 HARDING RD,SUITE 435,NASHVILLE,TN,37205,363LA2100X
3,Acute Care,347,24337,0.014258,1508892688,1.0,None,PEMBRIDGE,RICHARD,L,None,JR.,NP,2010 CHURCH ST,SUITE 201,NASHVILLE,TN,37203,363LA2100X
4,Acute Care,331,24337,0.013601,1811258213,1.0,None,HILL,KIMBERLY,WALDROP,MRS.,None,NP,4230 HARDING PIKE,SUITE 503,NASHVILLE,TN,37205,363LA2100X

In [81]:
None_Vandy_byspecialization_sqlite[None_Vandy_byspecialization_sqlite['specialization'] == 'Family'][['specialization_referral_ratio','provider_first_name','provider_last_name_(legal_name)']].head()

,specialization_referral_ratio,provider_first_name,provider_last_name_(legal_name)
422,0.014820,TIMOTHY,DICKEY
423,0.010377,JILLIAN,DIMOND
424,0.010276,KERI,GALBREATH
425,0.010106,TINA,DIEROLF
426,0.009903,LINDSEY,CHAPMAN

In [82]:
None_Vandy_byspecialization_sqlite[None_Vandy_byspecialization_sqlite['specialization'] == 'Orthopaedic Surgery of the Spine'][['specialization_referral_ratio','provider_first_name','provider_last_name_(legal_name)']].head()

,specialization_referral_ratio,provider_first_name,provider_last_name_(legal_name)
967,0.154662,JOHN,KLEKAMP
968,0.130982,MICHAEL,MCNAMARA
969,0.118648,ERION,QAMIRANI
970,0.087074,LAWRENCE,BABAT
971,0.063641,JAMES,FISH

In [71]:
d = None_Vandy_byspecialization_sqlite.groupby('specialization')['npi'].count().sort_values(ascending=False)
df = pd.DataFrame(data=d) 
df

                                                    npi
specialization
Family                                              286
Diagnostic Radiology                                143
Cardiovascular Disease                               65
Acute Care                                           60
Pulmonary Disease                                    55
Psychiatry                                           45
Anatomic Pathology & Clinical Pathology              42
Gastroenterology                                     39
Neurology                                            38
Medical                                              37
Adult Health                                         32
Psychiatric/Mental Health                            24
Vascular Surgery                                     23
Surgical                                             22
Interventional Cardiology                            21
Hematology & Oncology                                19
Critical Care Medicine                               17
Infectious Disease                                   16
Radiation Oncology                                   13
Emergency Medical Services                           13
Sports Medicine                                      12
Orthopaedic Surgery of the Spine                     12
Endocrinology, Diabetes & Metabolism                 11
Nephrology                                           11
Women's Health                                        9
Gynecologic Oncology                                  8
Pain Medicine                                         8
Gynecology                                            8
Primary Care                                          8
Clinical                                              7
Hand Surgery                                          7
Medical Oncology                                      7
Foot & Ankle Surgery                                  6
Clinical Cardiac Electrophysiology                    6
Trauma Surgery                                        6
Gerontology                                           6
Advanced Heart Failure and Transplant Cardiology      6
Hospice and Palliative Medicine                       6
Female Pelvic Medicine and Reconstructive Surgery     5
Adult Reconstructive Orthopaedic Surgery              5
Neuroradiology                                        4
Vascular & Interventional Radiology                   4
Rheumatology                                          4
Adult Medicine                                        4
Plastic and Reconstructive Surgery                    3
Orthopaedic Trauma                                    3
Geriatric Medicine                                    3
Hematology                                            3
Foot and Ankle Surgery                                3
Primary Podiatric Medicine                            3
Addiction Medicine                                    3
Surgical Oncology                                     2
Obstetrics                                            2
Ophthalmic Plastic and Reconstructive Surgery         2
Interventional Pain Medicine                          2
Retina Specialist                                     2
Therapeutic Radiology                                 1
Sports Physician                                      1
Adolescent Medicine                                   1
Vascular Neurology                                    1
Surgery of the Hand                                   1
Sleep Medicine                                        1
Brain Injury Medicine                                 1
Plastic Surgery within the Head & Neck                1
Pediatric Hematology-Oncology                         1
Clinical Child & Adolescent                           1
Clinical Pathology/Laboratory Medicine                1
Counseling                                            1
Diagnostic Neuroimaging                               1
Allergy                                               1
Diagnostic Ultrasound                                 1
Family Health                                         1
General Practice                                      1
Medical-Surgical                                      1
Neuromuscular Medicine                                1
Oral and Maxillofacial Surgery                        1
Orthopedic                                            1
Otology & Neurotology                                 1
Pediatric Cardiology                                  1
Pediatric Emergency Medicine                          1
Neurology with Special Qualifications in Child ...    1

In [72]:
df.to_csv('competitors_specialization.csv')

In [75]:
len(None_Vandy_byspecialization_sqlite.groupby('specialization')['npi'].count().sort_values(ascending=False))

81